apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: actions.core.opdemo.net
spec:
  scope: Namespaced
  group: core.opdemo.net
  names:
    kind: Action
    plural: actions
    singular: action
    shortNames:
      - ac
  versions:
    - name: v1
      served: true
      storage: true
      subresources: { status: { } }  # comment/uncomment for experiments
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Phase
          type: string
          priority: 0
          jsonPath: .status.phase
          description: The current phase.
